/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKERROR_H
#define _MOCKERROR_H

#include "error.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockerror_Init(void);
void Mockerror_Destroy(void);
void Mockerror_Verify(void);




#define fatal_error_Expect(fmt) fatal_error_CMockExpect(__LINE__, fmt)
void fatal_error_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* fmt);

#endif
