/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockerror.h"

typedef struct _CMOCK_fatal_error_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_fmt;

} CMOCK_fatal_error_CALL_INSTANCE;

static struct MockerrorInstance
{
  CMOCK_MEM_INDEX_TYPE fatal_error_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockerror_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.fatal_error_CallInstance, cmock_line, "Function 'fatal_error' called less times than expected.");
}

void Mockerror_Init(void)
{
  Mockerror_Destroy();
}

void Mockerror_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void fatal_error(const char* fmt, ...)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fatal_error_CALL_INSTANCE* cmock_call_instance = (CMOCK_fatal_error_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fatal_error_CallInstance);
  Mock.fatal_error_CallInstance = CMock_Guts_MemNext(Mock.fatal_error_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'fatal_error' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_fmt, fmt, cmock_line, "Function 'fatal_error' called with unexpected value for argument 'fmt'.");
  }
}

void CMockExpectParameters_fatal_error(CMOCK_fatal_error_CALL_INSTANCE* cmock_call_instance, const char* fmt)
{
  cmock_call_instance->Expected_fmt = (char*)fmt;
}

void fatal_error_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* fmt)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fatal_error_CALL_INSTANCE));
  CMOCK_fatal_error_CALL_INSTANCE* cmock_call_instance = (CMOCK_fatal_error_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fatal_error_CallInstance = CMock_Guts_MemChain(Mock.fatal_error_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_fatal_error(cmock_call_instance, fmt);
}

