/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockseqdiag.h"

typedef struct _CMOCK_sdiag_async_evt_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  EVENT_ST* Expected_p;

} CMOCK_sdiag_async_evt_CALL_INSTANCE;

typedef struct _CMOCK_sdiag_state_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ulong Expected_smobj;
  ulong Expected_stobj;

} CMOCK_sdiag_state_CALL_INSTANCE;

typedef struct _CMOCK_sdiag_tmrevt_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ulong Expected_t;

} CMOCK_sdiag_tmrevt_CALL_INSTANCE;

typedef struct _CMOCK_sdiag_text_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_s;

} CMOCK_sdiag_text_CALL_INSTANCE;

typedef struct _CMOCK_sdiag_exec_act_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ulong Expected_ao;
  ulong Expected_act;

} CMOCK_sdiag_exec_act_CALL_INSTANCE;

typedef struct _CMOCK_sdiag_sync_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ulong Expected_f;
  ulong Expected_snr;
  ulong Expected_dest;

} CMOCK_sdiag_sync_CALL_INSTANCE;

typedef struct _CMOCK_seqdiag_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_seqdiag_init_CALL_INSTANCE;

static struct MockseqdiagInstance
{
  CMOCK_MEM_INDEX_TYPE sdiag_async_evt_CallInstance;
  CMOCK_MEM_INDEX_TYPE sdiag_state_CallInstance;
  CMOCK_MEM_INDEX_TYPE sdiag_tmrevt_CallInstance;
  CMOCK_MEM_INDEX_TYPE sdiag_text_CallInstance;
  CMOCK_MEM_INDEX_TYPE sdiag_exec_act_CallInstance;
  CMOCK_MEM_INDEX_TYPE sdiag_sync_CallInstance;
  CMOCK_MEM_INDEX_TYPE seqdiag_init_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockseqdiag_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sdiag_async_evt_CallInstance, cmock_line, "Function 'sdiag_async_evt' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sdiag_state_CallInstance, cmock_line, "Function 'sdiag_state' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sdiag_tmrevt_CallInstance, cmock_line, "Function 'sdiag_tmrevt' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sdiag_text_CallInstance, cmock_line, "Function 'sdiag_text' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sdiag_exec_act_CallInstance, cmock_line, "Function 'sdiag_exec_act' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sdiag_sync_CallInstance, cmock_line, "Function 'sdiag_sync' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.seqdiag_init_CallInstance, cmock_line, "Function 'seqdiag_init' called less times than expected.");
}

void Mockseqdiag_Init(void)
{
  Mockseqdiag_Destroy();
}

void Mockseqdiag_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void sdiag_async_evt(EVENT_ST* p)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sdiag_async_evt_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_async_evt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sdiag_async_evt_CallInstance);
  Mock.sdiag_async_evt_CallInstance = CMock_Guts_MemNext(Mock.sdiag_async_evt_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sdiag_async_evt' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_p), (void*)(p), sizeof(EVENT_ST), cmock_line, "Function 'sdiag_async_evt' called with unexpected value for argument 'p'.");
  }
}

void CMockExpectParameters_sdiag_async_evt(CMOCK_sdiag_async_evt_CALL_INSTANCE* cmock_call_instance, EVENT_ST* p)
{
  cmock_call_instance->Expected_p = p;
}

void sdiag_async_evt_CMockExpect(UNITY_LINE_TYPE cmock_line, EVENT_ST* p)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sdiag_async_evt_CALL_INSTANCE));
  CMOCK_sdiag_async_evt_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_async_evt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sdiag_async_evt_CallInstance = CMock_Guts_MemChain(Mock.sdiag_async_evt_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_sdiag_async_evt(cmock_call_instance, p);
}

void sdiag_state(ulong smobj, ulong stobj)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sdiag_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sdiag_state_CallInstance);
  Mock.sdiag_state_CallInstance = CMock_Guts_MemNext(Mock.sdiag_state_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sdiag_state' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_smobj), (void*)(&smobj), sizeof(ulong), cmock_line, "Function 'sdiag_state' called with unexpected value for argument 'smobj'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_stobj), (void*)(&stobj), sizeof(ulong), cmock_line, "Function 'sdiag_state' called with unexpected value for argument 'stobj'.");
  }
}

void CMockExpectParameters_sdiag_state(CMOCK_sdiag_state_CALL_INSTANCE* cmock_call_instance, ulong smobj, ulong stobj)
{
  memcpy(&cmock_call_instance->Expected_smobj, &smobj, sizeof(ulong));
  memcpy(&cmock_call_instance->Expected_stobj, &stobj, sizeof(ulong));
}

void sdiag_state_CMockExpect(UNITY_LINE_TYPE cmock_line, ulong smobj, ulong stobj)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sdiag_state_CALL_INSTANCE));
  CMOCK_sdiag_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sdiag_state_CallInstance = CMock_Guts_MemChain(Mock.sdiag_state_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_sdiag_state(cmock_call_instance, smobj, stobj);
}

void sdiag_tmrevt(ulong t)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sdiag_tmrevt_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_tmrevt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sdiag_tmrevt_CallInstance);
  Mock.sdiag_tmrevt_CallInstance = CMock_Guts_MemNext(Mock.sdiag_tmrevt_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sdiag_tmrevt' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_t), (void*)(&t), sizeof(ulong), cmock_line, "Function 'sdiag_tmrevt' called with unexpected value for argument 't'.");
  }
}

void CMockExpectParameters_sdiag_tmrevt(CMOCK_sdiag_tmrevt_CALL_INSTANCE* cmock_call_instance, ulong t)
{
  memcpy(&cmock_call_instance->Expected_t, &t, sizeof(ulong));
}

void sdiag_tmrevt_CMockExpect(UNITY_LINE_TYPE cmock_line, ulong t)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sdiag_tmrevt_CALL_INSTANCE));
  CMOCK_sdiag_tmrevt_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_tmrevt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sdiag_tmrevt_CallInstance = CMock_Guts_MemChain(Mock.sdiag_tmrevt_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_sdiag_tmrevt(cmock_call_instance, t);
}

void sdiag_text(const char* s)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sdiag_text_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_text_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sdiag_text_CallInstance);
  Mock.sdiag_text_CallInstance = CMock_Guts_MemNext(Mock.sdiag_text_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sdiag_text' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, "Function 'sdiag_text' called with unexpected value for argument 's'.");
  }
}

void CMockExpectParameters_sdiag_text(CMOCK_sdiag_text_CALL_INSTANCE* cmock_call_instance, const char* s)
{
  cmock_call_instance->Expected_s = (char*)s;
}

void sdiag_text_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* s)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sdiag_text_CALL_INSTANCE));
  CMOCK_sdiag_text_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_text_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sdiag_text_CallInstance = CMock_Guts_MemChain(Mock.sdiag_text_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_sdiag_text(cmock_call_instance, s);
}

void sdiag_exec_act(ulong ao, ulong act)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sdiag_exec_act_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_exec_act_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sdiag_exec_act_CallInstance);
  Mock.sdiag_exec_act_CallInstance = CMock_Guts_MemNext(Mock.sdiag_exec_act_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sdiag_exec_act' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ao), (void*)(&ao), sizeof(ulong), cmock_line, "Function 'sdiag_exec_act' called with unexpected value for argument 'ao'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_act), (void*)(&act), sizeof(ulong), cmock_line, "Function 'sdiag_exec_act' called with unexpected value for argument 'act'.");
  }
}

void CMockExpectParameters_sdiag_exec_act(CMOCK_sdiag_exec_act_CALL_INSTANCE* cmock_call_instance, ulong ao, ulong act)
{
  memcpy(&cmock_call_instance->Expected_ao, &ao, sizeof(ulong));
  memcpy(&cmock_call_instance->Expected_act, &act, sizeof(ulong));
}

void sdiag_exec_act_CMockExpect(UNITY_LINE_TYPE cmock_line, ulong ao, ulong act)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sdiag_exec_act_CALL_INSTANCE));
  CMOCK_sdiag_exec_act_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_exec_act_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sdiag_exec_act_CallInstance = CMock_Guts_MemChain(Mock.sdiag_exec_act_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_sdiag_exec_act(cmock_call_instance, ao, act);
}

void sdiag_sync(ulong f, ulong snr, ulong dest)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sdiag_sync_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_sync_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sdiag_sync_CallInstance);
  Mock.sdiag_sync_CallInstance = CMock_Guts_MemNext(Mock.sdiag_sync_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sdiag_sync' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_f), (void*)(&f), sizeof(ulong), cmock_line, "Function 'sdiag_sync' called with unexpected value for argument 'f'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_snr), (void*)(&snr), sizeof(ulong), cmock_line, "Function 'sdiag_sync' called with unexpected value for argument 'snr'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dest), (void*)(&dest), sizeof(ulong), cmock_line, "Function 'sdiag_sync' called with unexpected value for argument 'dest'.");
  }
}

void CMockExpectParameters_sdiag_sync(CMOCK_sdiag_sync_CALL_INSTANCE* cmock_call_instance, ulong f, ulong snr, ulong dest)
{
  memcpy(&cmock_call_instance->Expected_f, &f, sizeof(ulong));
  memcpy(&cmock_call_instance->Expected_snr, &snr, sizeof(ulong));
  memcpy(&cmock_call_instance->Expected_dest, &dest, sizeof(ulong));
}

void sdiag_sync_CMockExpect(UNITY_LINE_TYPE cmock_line, ulong f, ulong snr, ulong dest)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sdiag_sync_CALL_INSTANCE));
  CMOCK_sdiag_sync_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdiag_sync_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sdiag_sync_CallInstance = CMock_Guts_MemChain(Mock.sdiag_sync_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_sdiag_sync(cmock_call_instance, f, snr, dest);
}

void seqdiag_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_seqdiag_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_seqdiag_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.seqdiag_init_CallInstance);
  Mock.seqdiag_init_CallInstance = CMock_Guts_MemNext(Mock.seqdiag_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'seqdiag_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void seqdiag_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_seqdiag_init_CALL_INSTANCE));
  CMOCK_seqdiag_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_seqdiag_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.seqdiag_init_CallInstance = CMock_Guts_MemChain(Mock.seqdiag_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

