<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="../libs/seqdiag/parser.js" ></script>
    <script type="text/javascript" src="../libs/seqdiag.js" ></script>
</head>
<body>
    <figure id="diag"></figure>
    <script type="text/x-seqdiag" id="seqdiag-text">
		seqdiag
		{
			// INSERT SEQUENCE HERE
        }
    </script>
    <script type="text/javascript">
        window.onload = function() {
            var target = document.getElementById("seqdiag-text");
            var ast = SeqdiagParser.parse(target.innerText);
            var diagram = Seqdiag.DiagramBuilder.build(ast);
            var svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
            svg.setAttribute("width", "1024");
            svg.setAttribute("height", "200");
            var drawer = new Seqdiag.Drawer.SVG(diagram, svg, document);
            drawer.draw();
            var figure = document.getElementById('diag');
            figure.appendChild(svg);
        };
    </script>
</body>
</html>

