/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mocktzlog.h"

typedef struct _CMOCK_lprintf_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_fmt;

} CMOCK_lprintf_CALL_INSTANCE;

typedef struct _CMOCK_start_log_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_fname;

} CMOCK_start_log_CALL_INSTANCE;

static struct MocktzlogInstance
{
  CMOCK_MEM_INDEX_TYPE lprintf_CallInstance;
  CMOCK_MEM_INDEX_TYPE start_log_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocktzlog_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.lprintf_CallInstance, cmock_line, "Function 'lprintf' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.start_log_CallInstance, cmock_line, "Function 'start_log' called less times than expected.");
}

void Mocktzlog_Init(void)
{
  Mocktzlog_Destroy();
}

void Mocktzlog_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void lprintf(const char* fmt, ...)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lprintf_CALL_INSTANCE* cmock_call_instance = (CMOCK_lprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lprintf_CallInstance);
  Mock.lprintf_CallInstance = CMock_Guts_MemNext(Mock.lprintf_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'lprintf' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_fmt, fmt, cmock_line, "Function 'lprintf' called with unexpected value for argument 'fmt'.");
  }
}

void CMockExpectParameters_lprintf(CMOCK_lprintf_CALL_INSTANCE* cmock_call_instance, const char* fmt)
{
  cmock_call_instance->Expected_fmt = (char*)fmt;
}

void lprintf_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* fmt)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lprintf_CALL_INSTANCE));
  CMOCK_lprintf_CALL_INSTANCE* cmock_call_instance = (CMOCK_lprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lprintf_CallInstance = CMock_Guts_MemChain(Mock.lprintf_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_lprintf(cmock_call_instance, fmt);
}

void start_log(const char* fname)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_start_log_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_log_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.start_log_CallInstance);
  Mock.start_log_CallInstance = CMock_Guts_MemNext(Mock.start_log_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'start_log' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_fname, fname, cmock_line, "Function 'start_log' called with unexpected value for argument 'fname'.");
  }
}

void CMockExpectParameters_start_log(CMOCK_start_log_CALL_INSTANCE* cmock_call_instance, const char* fname)
{
  cmock_call_instance->Expected_fname = (char*)fname;
}

void start_log_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* fname)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_start_log_CALL_INSTANCE));
  CMOCK_start_log_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_log_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.start_log_CallInstance = CMock_Guts_MemChain(Mock.start_log_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_start_log(cmock_call_instance, fname);
}

