/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTZLOG_H
#define _MOCKTZLOG_H

#include "tzlog.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mocktzlog_Init(void);
void Mocktzlog_Destroy(void);
void Mocktzlog_Verify(void);




#define lprintf_Expect(fmt) lprintf_CMockExpect(__LINE__, fmt)
void lprintf_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* fmt);
#define start_log_Expect(fname) start_log_CMockExpect(__LINE__, fname)
void start_log_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* fname);

#endif
