/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMDEBUG_H
#define _MOCKMDEBUG_H

#include "mdebug.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockmdebug_Init(void);
void Mockmdebug_Destroy(void);
void Mockmdebug_Verify(void);




#define dprintf_Expect(fmt) dprintf_CMockExpect(__LINE__, fmt)
void dprintf_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* fmt);

#endif
